//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fighters_DatabaseEntities : DbContext
    {
        public Fighters_DatabaseEntities()
            : base("name=Fighters_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fighters> Fighters { get; set; }
        public virtual DbSet<Promoutions> Promoutions { get; set; }
        public virtual DbSet<Table_Connections> Table_Connections { get; set; }
        public virtual DbSet<Weight_Classes> Weight_Classes { get; set; }
    }
}
