//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Connections
    {
        public int Promoutions_ID { get; set; }
        public int Weight_Class_ID { get; set; }
        public int Connection_ID { get; set; }
    
        public virtual Promoutions Promoutions { get; set; }
        public virtual Weight_Classes Weight_Classes { get; set; }
    }
}
